# lib/suppify/bindings.rb — the バインディング layer: per-VM C renderers that
# surface suppify's neutral C functions as top-level Ruby methods. Each
# renderer touches only the neutral header — no spinel type appears here.
# One module per VM ABI: CRuby (ruby.h), Mruby (full-mruby C API,
# PICORB_VM_MRUBY), Mrubyc (mruby/c VM, PICORB_VM_MRUBYC).
#
# Only exports with a neutral scalar C entry are surfaced. A method whose
# RBS gives it an Array/Hash/Symbol parameter or return has no scalar entry
# to wrap (its contract is the flat MessagePack entry, which a VM caller
# does not need -- it can pass the Ruby objects directly to an interpreted
# method), so it is skipped here rather than breaking the gem's build.
require "suppify/core"

module Suppify
  module Binding
    module_function

    # The exports a VM binding can wrap: those with a neutral scalar C entry.
    def neutral(exports) = exports.select { |e| e["neutral"] != false }

    # Generates the C source for a CRuby native extension that surfaces
    # suppify's neutral C functions as top-level Ruby methods (rb_define_global_
    # function, matching the top-level `def` in the source).
    module CRuby
      module_function

      # in-arg conversion (VALUE argN -> neutral C), keyed by NeutralType.kind
      IN = {
        int:    ->(v) { "(intptr_t)NUM2LONG(#{v})" },
        float:  ->(v) { "NUM2DBL(#{v})" },
        string: ->(v) { "StringValueCStr(#{v})" },
        bool:   ->(v) { "(RTEST(#{v}) ? 1 : 0)" },
      }.freeze

      # return conversion (neutral C `r` -> VALUE), keyed by NeutralType.kind.
      # :string is a lambda (not a fixed string) because it needs the
      # per-library str_len bridge: rb_str_new_cstr is strlen-based and
      # would silently truncate a return value at an embedded NUL.
      OUT = {
        int:    ->(_lib_name) { "return LONG2NUM((long)r);" },
        float:  ->(_lib_name) { "return DBL2NUM(r);" },
        string: ->(lib_name) { "return rb_str_new(r, #{lib_name}_str_len(r));" },
        bool:   ->(_lib_name) { "return r ? Qtrue : Qfalse;" },
        void:   ->(_lib_name) { "return Qnil;" },
      }.freeze

      def render(lib_name, exports)
        exports = Binding.neutral(exports)
        out = +"/* Generated by suppify (CRuby binding) */\n"
        out << "#include <ruby.h>\n"
        out << "#include \"#{lib_name}.h\"\n\n"
        exports.each { |e| out << wrapper(lib_name, e) << "\n" }
        out << init(lib_name, exports)
        out
      end

      def wrapper(lib_name, e)
        name   = e["public"]
        sig    = e["sig"]
        params = sig.params
        vargs  = params.each_index.map { |i| "VALUE a#{i}" }
        siglist = (["VALUE self"] + vargs).join(", ")
        call_args = params.each_with_index.map { |(t, _), i| IN.fetch(NeutralType.kind(t)).call("a#{i}") }
        ret_kind  = NeutralType.kind(sig.return_type)

        b = +"static VALUE suppi_rb_#{name}(#{siglist}) {\n"
        if ret_kind == :void
          b << "    #{name}(#{call_args.join(', ')});\n"
        else
          b << "    #{NeutralType.map(sig.return_type)} r = #{name}(#{call_args.join(', ')});\n"
        end
        b << "    if (#{lib_name}_error()) rb_raise(rb_eRuntimeError, \"%s\", #{lib_name}_error_message());\n"
        b << "    #{OUT.fetch(ret_kind).call(lib_name)}\n"
        b << "}\n"
        b
      end

      def init(lib_name, exports)
        b = +"void Init_#{lib_name}(void) {\n"
        b << "    #{lib_name}_init();\n"
        exports.each do |e|
          b << "    rb_define_global_function(\"#{e['public']}\", suppi_rb_#{e['public']}, #{e['sig'].params.length});\n"
        end
        b << "}\n"
        b
      end
    end

    # Generates the C source for a PicoRuby/mruby gem that surfaces suppify's
    # neutral C functions as top-level (Kernel) Ruby methods, matching the
    # top-level `def` in the source. Uses the mruby C API (mrb_get_args format
    # strings), distinct from the CRuby binding; only the neutral header is
    # touched. Targets the PICORB_VM_MRUBY VM (mrb_state* init convention).
    module Mruby
      module_function

      # mrb_get_args format char + C local type, keyed by NeutralType.kind
      GET = {
        int:    { fmt: "i", type: "mrb_int" },
        float:  { fmt: "f", type: "mrb_float" },
        string: { fmt: "z", type: "const char *" },
        bool:   { fmt: "b", type: "mrb_bool" },
      }.freeze

      # neutral-arg cast applied when calling the neutral function, by kind
      CAST = {
        int: "(intptr_t)", float: "", string: "", bool: "(int)",
      }.freeze

      # return conversion (neutral C `r` -> mrb_value), by kind. :string is a
      # lambda (not a fixed string) because it needs the per-library str_len
      # bridge: mrb_str_new_cstr is strlen-based and would silently truncate
      # a return value at an embedded NUL.
      OUT = {
        int:    ->(_lib_name) { "return mrb_fixnum_value((mrb_int)r);" },
        float:  ->(_lib_name) { "return mrb_float_value(mrb, r);" },
        string: ->(lib_name) { "return mrb_str_new(mrb, r, #{lib_name}_str_len(r));" },
        bool:   ->(_lib_name) { "return mrb_bool_value(r);" },
        void:   ->(_lib_name) { "return mrb_nil_value();" },
      }.freeze

      def render(header_name, init_func, exports)
        exports = Binding.neutral(exports)
        out = +"/* Generated by suppify (mruby/PicoRuby binding) */\n"
        out << "#include <mruby.h>\n"
        out << "#include <mruby/string.h>\n"
        out << "#include \"#{header_name}.h\"\n\n"
        exports.each { |e| out << wrapper(header_name, e) << "\n" }
        out << gem_init(header_name, init_func, exports)
        out
      end

      def wrapper(lib_name, e)
        name   = e["public"]
        sig    = e["sig"]
        params = sig.params
        kinds  = params.map { |t, _| NeutralType.kind(t) }
        ret_kind = NeutralType.kind(sig.return_type)

        b = +"static mrb_value mrb_suppi_#{name}(mrb_state *mrb, mrb_value self) {\n"
        unless params.empty?
          b << "    #{decls(kinds)}\n"
          fmt  = kinds.map { |k| GET[k][:fmt] }.join
          addrs = kinds.each_index.map { |i| "&a#{i}" }.join(", ")
          b << "    mrb_get_args(mrb, \"#{fmt}\", #{addrs});\n"
        end
        call_args = kinds.each_index.map { |i| "#{CAST[kinds[i]]}a#{i}" }.join(", ")
        if ret_kind == :void
          b << "    #{name}(#{call_args});\n"
        else
          b << "    #{NeutralType.map(sig.return_type)} r = #{name}(#{call_args});\n"
        end
        b << "    if (#{lib_name}_error()) mrb_raise(mrb, E_RUNTIME_ERROR, #{lib_name}_error_message());\n"
        b << "    #{OUT.fetch(ret_kind).call(lib_name)}\n"
        b << "}\n"
        b
      end

      # C declarations for the get_args locals, one per parameter. A pointer
      # type (e.g. "const char *") already ends in "*", so no extra space is
      # inserted before the variable name; other types get a separating space.
      def decls(kinds)
        kinds.each_index.map do |i|
          type = GET[kinds[i]][:type]
          sep = type.end_with?("*") ? "" : " "
          "#{type}#{sep}a#{i};"
        end.join(" ")
      end

      def gem_init(lib_name, init_func, exports)
        final_func = init_func.sub(/_gem_init\z/, "_gem_final")
        b = +"void #{init_func}(mrb_state *mrb) {\n"
        b << "    #{lib_name}_init();\n"
        exports.each do |e|
          n = e["public"]
          arity = e["sig"].params.length
          b << "    mrb_define_method(mrb, mrb->kernel_module, \"#{n}\", mrb_suppi_#{n}, MRB_ARGS_REQ(#{arity}));\n"
        end
        b << "}\n\n"
        # picoruby's aggregate gem_init.c calls both init and final.
        b << "void #{final_func}(mrb_state *mrb) { (void)mrb; }\n"
        b
      end
    end

    # Generates the C source for a PicoRuby mrbgem that surfaces suppify's
    # neutral C functions as top-level (Object) Ruby methods on the mruby/c
    # (mrubyc) VM -- the VM PicoRuby actually runs under PICORB_VM_MRUBYC
    # (the common case for microcontroller targets; see Binding::Mruby for
    # the full-mruby/PICORB_VM_MRUBY sibling). mrubyc has no mrb_get_args-style
    # helper, so each wrapper hand-checks v[].tt and raises ArgumentError on
    # mismatch, matching this ecosystem's other hand-written mrubyc gems
    # (e.g. picoruby-irq's src/mrubyc/irq.c).
    module Mrubyc
      module_function

      # mrbc_value .tt check + C accessor expression, keyed by NeutralType.kind.
      # :bool has no entry -- Ruby truthiness (nil/false vs anything else)
      # doesn't type-check, mirroring mrb_get_args's "b" format.
      ARG = {
        int:    { tt: "MRBC_TT_INTEGER", get: ->(i) { "v[#{i}].i" }, type: "mrb_int" },
        float:  { tt: "MRBC_TT_FLOAT",   get: ->(i) { "v[#{i}].d" }, type: "mrb_float" },
        string: { tt: "MRBC_TT_STRING",  get: ->(i) { "(const char *)v[#{i}].string->data" }, type: "const char *" },
      }.freeze

      # neutral-arg cast applied when calling the neutral function, by kind
      CAST = { int: "(intptr_t)", float: "", string: "", bool: "(int)" }.freeze

      # return conversion (neutral C `r` -> SET_*_RETURN statement), by kind.
      # :string is a lambda for the same str_len bridge Binding::Mruby uses:
      # a length-explicit constructor so an embedded NUL isn't truncated.
      OUT = {
        int:    ->(_lib_name) { "SET_INT_RETURN(r);" },
        float:  ->(_lib_name) { "SET_FLOAT_RETURN(r);" },
        string: ->(lib_name) { "SET_RETURN(mrbc_string_new(vm, r, #{lib_name}_str_len(r)));" },
        bool:   ->(_lib_name) { "SET_BOOL_RETURN(r);" },
        void:   ->(_lib_name) { "SET_NIL_RETURN();" },
      }.freeze

      def render(header_name, init_func, exports)
        exports = Binding.neutral(exports)
        out = +"/* Generated by suppify (mruby/c PicoRuby binding) */\n"
        out << "#include <mrubyc.h>\n"
        # mrb_state is only used as an opaque, never-dereferenced pointer
        # parameter in gem_init's aggregate-table signature (see
        # gem_init below). Defining it locally as `void`, rather than
        # pulling in <mruby.h>, avoids a real collision: <mruby.h> and
        # <mrubyc.h> both define mrb_int/mrb_float/E_*_ERROR for legacy
        # compat, with incompatible types. This mirrors the
        # `#define mrb_state void` shim picoruby-mrubyc/include/mruby.h
        # itself uses for the same reason.
        out << "#define mrb_state void\n"
        out << "#include \"#{header_name}.h\"\n\n"
        exports.each { |e| out << wrapper(header_name, e) << "\n" }
        out << gem_init(header_name, init_func, exports)
        out
      end

      def wrapper(lib_name, e)
        name   = e["public"]
        sig    = e["sig"]
        params = sig.params
        kinds  = params.map { |t, _| NeutralType.kind(t) }
        ret_kind = NeutralType.kind(sig.return_type)

        b = +"static void c_suppi_#{name}(struct VM *vm, mrbc_value v[], int argc) {\n"
        b << "    if (argc != #{kinds.length}) { mrbc_raise(vm, MRBC_CLASS(ArgumentError), \"wrong number of arguments\"); return; }\n"
        kinds.each_index { |i| b << arg_check(i, kinds[i]) }
        decls = kinds.each_index.map { |i| decl(i, kinds[i]) }.join(" ")
        b << "    #{decls}\n" unless decls.empty?
        call_args = kinds.each_index.map { |i| "#{CAST[kinds[i]]}a#{i}" }.join(", ")
        if ret_kind == :void
          b << "    #{name}(#{call_args});\n"
        else
          b << "    #{NeutralType.map(sig.return_type)} r = #{name}(#{call_args});\n"
        end
        b << "    if (#{lib_name}_error()) { mrbc_raise(vm, MRBC_CLASS(RuntimeError), #{lib_name}_error_message()); return; }\n"
        b << "    #{OUT.fetch(ret_kind).call(lib_name)}\n"
        b << "}\n"
        b
      end

      # v[0] is self, so parameter i lives at v[i+1].
      def arg_check(i, kind)
        return "" if kind == :bool

        spec = ARG.fetch(kind)
        "    if (v[#{i + 1}].tt != #{spec[:tt]}) { mrbc_raise(vm, MRBC_CLASS(ArgumentError), \"wrong argument type\"); return; }\n"
      end

      def decl(i, kind)
        n = i + 1
        if kind == :bool
          "int a#{i} = (v[#{n}].tt != MRBC_TT_NIL && v[#{n}].tt != MRBC_TT_FALSE);"
        else
          spec = ARG.fetch(kind)
          sep = spec[:type].end_with?("*") ? "" : " "
          "#{spec[:type]}#{sep}a#{i} = #{spec[:get].call(n)};"
        end
      end

      # The registration entry that actually runs on mrubyc firmware:
      # picoruby-require's generated prebuilt_gems[] table maps
      # `require '<lib>'` to `mrbc_<lib>_init(mrbc_vm *vm)` (name derived
      # from the gem dir name by its collect_gems task) and then loads the
      # gem's mrblib bytecode. Registration targets Object via
      # mrbc_define_method(0, 0, ...) -- same convention as
      # picoruby-mrubyc's own rrt0.c -- so vm is unused.
      #
      # mrb_<gem>_gem_init stays defined (delegating) because the
      # mruby-style aggregate gem_init.c in the build tree references it;
      # that object is not pulled into mrubyc firmware links today, but a
      # build that does link it must not hit an undefined symbol. mrb_state
      # degrades to `void` under PICORB_VM_MRUBYC (see the mruby.h
      # compatibility shim note in render).
      def gem_init(lib_name, init_func, exports)
        mrbc_init = "mrbc_#{lib_name.tr('-', '_')}_init"
        final_func = init_func.sub(/_gem_init\z/, "_gem_final")
        b = +"void #{mrbc_init}(mrbc_vm *vm) {\n"
        b << "    (void)vm;\n"
        b << "    #{lib_name}_init();\n"
        exports.each do |e|
          n = e["public"]
          b << "    mrbc_define_method(0, 0, \"#{n}\", c_suppi_#{n});\n"
        end
        b << "}\n\n"
        b << "void #{init_func}(mrb_state *mrb) { (void)mrb; #{mrbc_init}(0); }\n\n"
        b << "void #{final_func}(mrb_state *mrb) { (void)mrb; }\n"
        b
      end
    end
  end
end
