# lib/suppify/symbol_prefix.rb
require "fileutils"
require "tmpdir"
require "suppify/runtime_sources"

module Suppify
  # spinel's vendored runtime (sp_gc.c, sp_alloc.c, ...) exposes ~600 global
  # (externally-linked) symbols shared by every generated program that links
  # against it. Fine for spinel's normal one-program-per-binary use, but two
  # suppify libraries linked into the same binary/firmware image would each
  # bring their own copy of that runtime and collide at link time. This
  # module discovers the exact symbol set from a real compile (rather than
  # guessing prefixes) and renders a C prelude that #defines each one to a
  # lib_name-specific name, so N suppify libraries can coexist.
  module SymbolPrefix
    module_function

    # Compiles the flattened runtime sources with the host cc (a throwaway,
    # discovery-only build -- the actual target build, possibly a cross
    # toolchain, does the real compile later) and returns every externally
    # linked (non-static) symbol name spinel's runtime defines. Symbol names
    # are portable across target architectures; only the object code differs.
    # sp_ctx_swap (spinel's Fiber context-switch primitive) is defined via a
    # file-scope __asm__ string in sp_fiber.c with its symbol name hardcoded
    # as a C string literal -- #define substitution never reaches inside a
    # string, so renaming it would rename call sites but not the definition,
    # producing an undefined-symbol link error. It's stateless and
    # bit-identical regardless of which library compiles it, so leaving it
    # shared (unrenamed) is safe; it's the one runtime symbol excluded here.
    EXCLUDED = %w[sp_ctx_swap].freeze

    # sp_runtime.h -- included only by each generated program's own TU, not
    # by any of the 25 lib/*.c sources -- embeds ~200 non-static function
    # bodies directly (spinel's normal build compiles it into exactly one
    # program TU per binary). Every suppify library's generated .c includes
    # it too, so scanning only lib/*.c misses these entirely, leaving them
    # unrenamed and colliding across libraries (confirmed empirically). This
    # stub mirrors what a generated TU provides (the three symbol/class
    # lookups spinel expects the program itself to define, always static
    # there) so compiling it surfaces the header-embedded symbols too.
    DISCOVERY_STUB = <<~C
      #include "sp_runtime.h"
      static const char *sp_sym_to_s(sp_sym id) { (void)id; return ""; }
      static sp_sym sp_sym_intern(const char *s) { (void)s; return (sp_sym)0; }
      static const char *sp_class_to_s(sp_Class c) { (void)c; return ""; }
    C

    # Compiled without SP_THREADS, so the handful of globals unique to
    # spinel's threaded runtime variant (sp_heap_lock, sp_sched_sleep,
    # sp_sched_wait_io) go unrenamed if the real target build ever compiles
    # suppify's bundled runtime with SP_THREADS -- nothing in suppify does
    # today (no target passes it through), so this is a dormant gap, not an
    # active one.
    def discover_runtime_symbols(spinel_lib)
      Dir.mktmpdir do |dir|
        RuntimeSources.copy_flat(spinel_lib, dir)
        File.write(File.join(dir, "_discovery_stub.c"), DISCOVERY_STUB)
        objs = Dir[File.join(dir, "*.c")].map do |c_path|
          o_path = c_path.sub(/\.c\z/, ".o")
          out = `cc -c #{c_path} -I#{dir} -o #{o_path} 2>&1`
          raise Error, "discovery compile failed for #{c_path}:\n#{out}" unless $?.success?
          o_path
        end
        parse_nm(`nm #{objs.join(' ')} 2>/dev/null`) - EXCLUDED
      end
    end

    # nm output is "<addr> <type> <name>"; an uppercase type letter means
    # external linkage (what we must rename), lowercase means file-local
    # (already collision-safe, left alone). Mach-O (macOS) prefixes every
    # symbol with an extra "_" that isn't part of the C identifier.
    def parse_nm(output)
      names = []
      output.each_line do |line|
        addr, type, name = line.split
        next unless addr && type && name && type =~ /\A[A-Z]\z/
        names << name.sub(/\A_/, "")
      end
      names.uniq.sort
    end

    KNOWN_HARMLESS_WARNINGS = %w[
      -Wunused-function
      -Wunused-variable
      -Wcomment
    ].freeze

    CLANG_ONLY_WARNINGS = %w[
      -Wmacro-redefined
      -Wmissing-noreturn
      -Wunterminated-string-initialization
      -Wshorten-64-to-32
    ].freeze

    # Force-included (-include) ahead of every .c file compiled for one
    # suppify library: renames every vendored runtime symbol to a lib_name-
    # prefixed name, and silences the vendored runtime's own harmless
    # warnings (portably -- clang-specific diagnostic names are guarded so a
    # plain-GCC cross toolchain, e.g. ESP32's, never sees an unknown pragma).
    def prelude(lib_name, symbols)
      out = +"/* Generated by suppify: per-library symbol namespacing + vendored-runtime warning triage. */\n"
      out << "#if defined(__clang__)\n"
      CLANG_ONLY_WARNINGS.each { |w| out << "#pragma clang diagnostic ignored \"#{w}\"\n" }
      out << "#endif\n"
      KNOWN_HARMLESS_WARNINGS.each { |w| out << "#pragma GCC diagnostic ignored \"#{w}\"\n" }
      symbols.each { |s| out << "#define #{s} #{lib_name}_#{s}\n" }
      out
    end
  end
end
