# lib/suppify/binding/cruby.rb
require "suppify/neutral_type"

module Suppify
  module Binding
    # Generates the C source for a CRuby native extension that surfaces
    # suppify's neutral C functions as top-level Ruby methods (rb_define_global_
    # function, matching the top-level `def` in the source). The wrappers only
    # touch the neutral header — no spinel type ever appears here.
    module CRuby
      module_function

      # in-arg conversion (VALUE argN -> neutral C), keyed by NeutralType.kind
      IN = {
        int:    ->(v) { "(intptr_t)NUM2LONG(#{v})" },
        float:  ->(v) { "NUM2DBL(#{v})" },
        string: ->(v) { "StringValueCStr(#{v})" },
        bool:   ->(v) { "(RTEST(#{v}) ? 1 : 0)" },
      }.freeze

      # return conversion (neutral C `r` -> VALUE), keyed by NeutralType.kind.
      # :string is a lambda (not a fixed string) because it needs the
      # per-library str_len bridge: rb_str_new_cstr is strlen-based and
      # would silently truncate a return value at an embedded NUL.
      OUT = {
        int:    ->(_lib_name) { "return LONG2NUM((long)r);" },
        float:  ->(_lib_name) { "return DBL2NUM(r);" },
        string: ->(lib_name) { "return rb_str_new(r, #{lib_name}_str_len(r));" },
        bool:   ->(_lib_name) { "return r ? Qtrue : Qfalse;" },
        void:   ->(_lib_name) { "return Qnil;" },
      }.freeze

      def render(lib_name, exports)
        out = +"/* Generated by suppify (CRuby binding) */\n"
        out << "#include <ruby.h>\n"
        out << "#include \"#{lib_name}.h\"\n\n"
        exports.each { |e| out << wrapper(lib_name, e) << "\n" }
        out << init(lib_name, exports)
        out
      end

      def wrapper(lib_name, e)
        name   = e["public"]
        sig    = e["sig"]
        params = sig.params
        vargs  = params.each_index.map { |i| "VALUE a#{i}" }
        siglist = (["VALUE self"] + vargs).join(", ")
        call_args = params.each_with_index.map { |(t, _), i| IN.fetch(NeutralType.kind(t)).call("a#{i}") }
        ret_kind  = NeutralType.kind(sig.return_type)

        b = +"static VALUE suppi_rb_#{name}(#{siglist}) {\n"
        if ret_kind == :void
          b << "    #{name}(#{call_args.join(', ')});\n"
        else
          b << "    #{NeutralType.map(sig.return_type)} r = #{name}(#{call_args.join(', ')});\n"
        end
        b << "    if (#{lib_name}_error()) rb_raise(rb_eRuntimeError, \"%s\", #{lib_name}_error_message());\n"
        b << "    #{OUT.fetch(ret_kind).call(lib_name)}\n"
        b << "}\n"
        b
      end

      def init(lib_name, exports)
        b = +"void Init_#{lib_name}(void) {\n"
        b << "    #{lib_name}_init();\n"
        exports.each do |e|
          b << "    rb_define_global_function(\"#{e['public']}\", suppi_rb_#{e['public']}, #{e['sig'].params.length});\n"
        end
        b << "}\n"
        b
      end
    end
  end
end
