# lib/suppify/binding/mrubyc.rb
require "suppify/neutral_type"

module Suppify
  module Binding
    # Generates the C source for a PicoRuby mrbgem that surfaces suppify's
    # neutral C functions as top-level (Object) Ruby methods on the mruby/c
    # (mrubyc) VM -- the VM PicoRuby actually runs under PICORB_VM_MRUBYC
    # (the common case for microcontroller targets; see Binding::Mruby for
    # the full-mruby/PICORB_VM_MRUBY sibling). mrubyc has no mrb_get_args-style
    # helper, so each wrapper hand-checks v[].tt and raises ArgumentError on
    # mismatch, matching this ecosystem's other hand-written mrubyc gems
    # (e.g. picoruby-irq's src/mrubyc/irq.c).
    module Mrubyc
      module_function

      # mrbc_value .tt check + C accessor expression, keyed by NeutralType.kind.
      # :bool has no entry -- Ruby truthiness (nil/false vs anything else)
      # doesn't type-check, mirroring mrb_get_args's "b" format.
      ARG = {
        int:    { tt: "MRBC_TT_INTEGER", get: ->(i) { "v[#{i}].i" }, type: "mrb_int" },
        float:  { tt: "MRBC_TT_FLOAT",   get: ->(i) { "v[#{i}].d" }, type: "mrb_float" },
        string: { tt: "MRBC_TT_STRING",  get: ->(i) { "(const char *)v[#{i}].string->data" }, type: "const char *" },
      }.freeze

      # neutral-arg cast applied when calling the neutral function, by kind
      CAST = { int: "(intptr_t)", float: "", string: "", bool: "(int)" }.freeze

      # return conversion (neutral C `r` -> SET_*_RETURN statement), by kind.
      # :string is a lambda for the same str_len bridge Binding::Mruby uses:
      # a length-explicit constructor so an embedded NUL isn't truncated.
      OUT = {
        int:    ->(_lib_name) { "SET_INT_RETURN(r);" },
        float:  ->(_lib_name) { "SET_FLOAT_RETURN(r);" },
        string: ->(lib_name) { "SET_RETURN(mrbc_string_new(vm, r, #{lib_name}_str_len(r)));" },
        bool:   ->(_lib_name) { "SET_BOOL_RETURN(r);" },
        void:   ->(_lib_name) { "SET_NIL_RETURN();" },
      }.freeze

      def render(header_name, init_func, exports)
        out = +"/* Generated by suppify (mruby/c PicoRuby binding) */\n"
        out << "#include <mrubyc.h>\n"
        # mrb_state is only used as an opaque, never-dereferenced pointer
        # parameter in gem_init's aggregate-table signature (see
        # gem_init below). Defining it locally as `void`, rather than
        # pulling in <mruby.h>, avoids a real collision: <mruby.h> and
        # <mrubyc.h> both define mrb_int/mrb_float/E_*_ERROR for legacy
        # compat, with incompatible types. This mirrors the
        # `#define mrb_state void` shim picoruby-mrubyc/include/mruby.h
        # itself uses for the same reason.
        out << "#define mrb_state void\n"
        out << "#include \"#{header_name}.h\"\n\n"
        exports.each { |e| out << wrapper(header_name, e) << "\n" }
        out << gem_init(header_name, init_func, exports)
        out
      end

      def wrapper(lib_name, e)
        name   = e["public"]
        sig    = e["sig"]
        params = sig.params
        kinds  = params.map { |t, _| NeutralType.kind(t) }
        ret_kind = NeutralType.kind(sig.return_type)

        b = +"static void c_suppi_#{name}(struct VM *vm, mrbc_value v[], int argc) {\n"
        b << "    if (argc != #{kinds.length}) { mrbc_raise(vm, MRBC_CLASS(ArgumentError), \"wrong number of arguments\"); return; }\n"
        kinds.each_index { |i| b << arg_check(i, kinds[i]) }
        decls = kinds.each_index.map { |i| decl(i, kinds[i]) }.join(" ")
        b << "    #{decls}\n" unless decls.empty?
        call_args = kinds.each_index.map { |i| "#{CAST[kinds[i]]}a#{i}" }.join(", ")
        if ret_kind == :void
          b << "    #{name}(#{call_args});\n"
        else
          b << "    #{NeutralType.map(sig.return_type)} r = #{name}(#{call_args});\n"
        end
        b << "    if (#{lib_name}_error()) { mrbc_raise(vm, MRBC_CLASS(RuntimeError), #{lib_name}_error_message()); return; }\n"
        b << "    #{OUT.fetch(ret_kind).call(lib_name)}\n"
        b << "}\n"
        b
      end

      # v[0] is self, so parameter i lives at v[i+1].
      def arg_check(i, kind)
        return "" if kind == :bool

        spec = ARG.fetch(kind)
        "    if (v[#{i + 1}].tt != #{spec[:tt]}) { mrbc_raise(vm, MRBC_CLASS(ArgumentError), \"wrong argument type\"); return; }\n"
      end

      def decl(i, kind)
        n = i + 1
        if kind == :bool
          "int a#{i} = (v[#{n}].tt != MRBC_TT_NIL && v[#{n}].tt != MRBC_TT_FALSE);"
        else
          spec = ARG.fetch(kind)
          sep = spec[:type].end_with?("*") ? "" : " "
          "#{spec[:type]}#{sep}a#{i} = #{spec[:get].call(n)};"
        end
      end

      # mrb_state degrades to `void` under PICORB_VM_MRUBYC (see
      # picoruby-mrubyc's own mruby.h compatibility shim) -- the param
      # exists only to match the aggregate gem lifecycle hook signature
      # every picoruby mrbgem's generated glue calls unconditionally.
      def gem_init(lib_name, init_func, exports)
        final_func = init_func.sub(/_gem_init\z/, "_gem_final")
        b = +"void #{init_func}(mrb_state *mrb) {\n"
        b << "    (void)mrb;\n"
        b << "    #{lib_name}_init();\n"
        exports.each do |e|
          n = e["public"]
          b << "    mrbc_define_method(0, 0, \"#{n}\", c_suppi_#{n});\n"
        end
        b << "}\n\n"
        b << "void #{final_func}(mrb_state *mrb) { (void)mrb; }\n"
        b
      end
    end
  end
end
