# lib/suppify/binding/mruby.rb
require "suppify/neutral_type"

module Suppify
  module Binding
    # Generates the C source for a PicoRuby/mruby gem that surfaces suppify's
    # neutral C functions as top-level (Kernel) Ruby methods, matching the
    # top-level `def` in the source. Uses the mruby C API (mrb_get_args format
    # strings), distinct from the CRuby binding; only the neutral header is
    # touched. Targets the PICORB_VM_MRUBY VM (mrb_state* init convention).
    module Mruby
      module_function

      # mrb_get_args format char + C local type, keyed by NeutralType.kind
      GET = {
        int:    { fmt: "i", type: "mrb_int" },
        float:  { fmt: "f", type: "mrb_float" },
        string: { fmt: "z", type: "const char *" },
        bool:   { fmt: "b", type: "mrb_bool" },
      }.freeze

      # neutral-arg cast applied when calling the neutral function, by kind
      CAST = {
        int: "(intptr_t)", float: "", string: "", bool: "(int)",
      }.freeze

      # return conversion (neutral C `r` -> mrb_value), by kind
      OUT = {
        int:    "return mrb_fixnum_value((mrb_int)r);",
        float:  "return mrb_float_value(mrb, r);",
        string: "return mrb_str_new_cstr(mrb, r);",
        bool:   "return mrb_bool_value(r);",
        void:   "return mrb_nil_value();",
      }.freeze

      def render(header_name, init_func, exports)
        out = +"/* Generated by suppify (mruby/PicoRuby binding) */\n"
        out << "#include <mruby.h>\n"
        out << "#include <mruby/string.h>\n"
        out << "#include \"#{header_name}.h\"\n\n"
        exports.each { |e| out << wrapper(e) << "\n" }
        out << gem_init(init_func, exports)
        out
      end

      def wrapper(e)
        name   = e["public"]
        sig    = e["sig"]
        params = sig.params
        kinds  = params.map { |t, _| NeutralType.kind(t) }
        ret_kind = NeutralType.kind(sig.return_type)

        b = +"static mrb_value mrb_suppi_#{name}(mrb_state *mrb, mrb_value self) {\n"
        unless params.empty?
          b << "    #{decls(kinds)}\n"
          fmt  = kinds.map { |k| GET[k][:fmt] }.join
          addrs = kinds.each_index.map { |i| "&a#{i}" }.join(", ")
          b << "    mrb_get_args(mrb, \"#{fmt}\", #{addrs});\n"
        end
        call_args = kinds.each_index.map { |i| "#{CAST[kinds[i]]}a#{i}" }.join(", ")
        if ret_kind == :void
          b << "    #{name}(#{call_args});\n"
        else
          b << "    #{NeutralType.map(sig.return_type)} r = #{name}(#{call_args});\n"
        end
        b << "    if (suppi_error()) mrb_raise(mrb, E_RUNTIME_ERROR, suppi_error_message());\n"
        b << "    #{OUT.fetch(ret_kind)}\n"
        b << "}\n"
        b
      end

      # C declarations for the get_args locals, grouped by type in first-seen
      # order: "mrb_int a0, a1;" for values, "const char *a0, *a1;" for pointers.
      def decls(kinds)
        groups = {} # type => [indices]
        kinds.each_with_index { |k, i| (groups[GET[k][:type]] ||= []) << i }
        groups.map do |type, idxs|
          if type.end_with?("*")
            base = type.sub(/\s*\*+\s*\z/, "") # "const char *" -> "const char"
            "#{base} #{idxs.map { |i| "*a#{i}" }.join(', ')};"
          else
            "#{type} #{idxs.map { |i| "a#{i}" }.join(', ')};"
          end
        end.join(" ")
      end

      def gem_init(init_func, exports)
        b = +"void #{init_func}(mrb_state *mrb) {\n"
        b << "    sp_lib_init();\n"
        exports.each do |e|
          n = e["public"]
          arity = e["sig"].params.length
          b << "    mrb_define_method(mrb, mrb->kernel_module, \"#{n}\", mrb_suppi_#{n}, MRB_ARGS_REQ(#{arity}));\n"
        end
        b << "}\n"
        b
      end
    end
  end
end
