# lib/suppify/binding/mruby.rb
require "suppify/neutral_type"

module Suppify
  module Binding
    # Generates the C source for a PicoRuby/mruby gem that surfaces suppify's
    # neutral C functions as top-level (Kernel) Ruby methods, matching the
    # top-level `def` in the source. Uses the mruby C API (mrb_get_args format
    # strings), distinct from the CRuby binding; only the neutral header is
    # touched. Targets the PICORB_VM_MRUBY VM (mrb_state* init convention).
    module Mruby
      module_function

      # mrb_get_args format char + C local type, keyed by NeutralType.kind
      GET = {
        int:    { fmt: "i", type: "mrb_int" },
        float:  { fmt: "f", type: "mrb_float" },
        string: { fmt: "z", type: "const char *" },
        bool:   { fmt: "b", type: "mrb_bool" },
      }.freeze

      # neutral-arg cast applied when calling the neutral function, by kind
      CAST = {
        int: "(intptr_t)", float: "", string: "", bool: "(int)",
      }.freeze

      # return conversion (neutral C `r` -> mrb_value), by kind. :string is a
      # lambda (not a fixed string) because it needs the per-library str_len
      # bridge: mrb_str_new_cstr is strlen-based and would silently truncate
      # a return value at an embedded NUL.
      OUT = {
        int:    ->(_lib_name) { "return mrb_fixnum_value((mrb_int)r);" },
        float:  ->(_lib_name) { "return mrb_float_value(mrb, r);" },
        string: ->(lib_name) { "return mrb_str_new(mrb, r, #{lib_name}_str_len(r));" },
        bool:   ->(_lib_name) { "return mrb_bool_value(r);" },
        void:   ->(_lib_name) { "return mrb_nil_value();" },
      }.freeze

      def render(header_name, init_func, exports)
        out = +"/* Generated by suppify (mruby/PicoRuby binding) */\n"
        out << "#include <mruby.h>\n"
        out << "#include <mruby/string.h>\n"
        out << "#include \"#{header_name}.h\"\n\n"
        exports.each { |e| out << wrapper(header_name, e) << "\n" }
        out << gem_init(header_name, init_func, exports)
        out
      end

      def wrapper(lib_name, e)
        name   = e["public"]
        sig    = e["sig"]
        params = sig.params
        kinds  = params.map { |t, _| NeutralType.kind(t) }
        ret_kind = NeutralType.kind(sig.return_type)

        b = +"static mrb_value mrb_suppi_#{name}(mrb_state *mrb, mrb_value self) {\n"
        unless params.empty?
          b << "    #{decls(kinds)}\n"
          fmt  = kinds.map { |k| GET[k][:fmt] }.join
          addrs = kinds.each_index.map { |i| "&a#{i}" }.join(", ")
          b << "    mrb_get_args(mrb, \"#{fmt}\", #{addrs});\n"
        end
        call_args = kinds.each_index.map { |i| "#{CAST[kinds[i]]}a#{i}" }.join(", ")
        if ret_kind == :void
          b << "    #{name}(#{call_args});\n"
        else
          b << "    #{NeutralType.map(sig.return_type)} r = #{name}(#{call_args});\n"
        end
        b << "    if (#{lib_name}_error()) mrb_raise(mrb, E_RUNTIME_ERROR, #{lib_name}_error_message());\n"
        b << "    #{OUT.fetch(ret_kind).call(lib_name)}\n"
        b << "}\n"
        b
      end

      # C declarations for the get_args locals, one per parameter. A pointer
      # type (e.g. "const char *") already ends in "*", so no extra space is
      # inserted before the variable name; other types get a separating space.
      def decls(kinds)
        kinds.each_index.map do |i|
          type = GET[kinds[i]][:type]
          sep = type.end_with?("*") ? "" : " "
          "#{type}#{sep}a#{i};"
        end.join(" ")
      end

      def gem_init(lib_name, init_func, exports)
        final_func = init_func.sub(/_gem_init\z/, "_gem_final")
        b = +"void #{init_func}(mrb_state *mrb) {\n"
        b << "    #{lib_name}_init();\n"
        exports.each do |e|
          n = e["public"]
          arity = e["sig"].params.length
          b << "    mrb_define_method(mrb, mrb->kernel_module, \"#{n}\", mrb_suppi_#{n}, MRB_ARGS_REQ(#{arity}));\n"
        end
        b << "}\n\n"
        # picoruby's aggregate gem_init.c calls both init and final.
        b << "void #{final_func}(mrb_state *mrb) { (void)mrb; }\n"
        b
      end
    end
  end
end
